"""Defined functions to plug into CI pipeline jobs."""


# This function serves as a template for building binary modules. To use it, make it
# a public function by removing the `_` prefix and edit it as necessary.
def _edit_conda_recipe(recipe_fname: str):
    """Makes necessary edition to the conda recipe file generated by grayskull."""
    # The recipe file is in a half-cooked YAML format.
    with open(recipe_fname) as fh:
        lines = fh.readlines()

    # Inserts extra line under the `host:` section to include more dependencies.
    for i, line in enumerate(lines, start=1):  # noqa: B007
        if "  host:" in line:
            break
    lines[i:i] = ["    - cmake-build-extension\n"]

    for i, line in enumerate(lines, start=1):  # noqa: B007
        if "  build:" in line:
            break
    lines[i:i] = ["    - {" "{ compiler('cxx') }" "}\n"]

    with open(recipe_fname, "w") as fh:
        fh.writelines(lines)
