abfe_ligands: null
atm_type: rbfe
atom_build_pathname: ~/github/ATom_OpenMM
cofactor_fpathname: ./001.prep/cofactors/GDP/cofactor.sdf
displ_vec: null
disregard_ratio: 0.3
dt: 0.004
exchange_interval: 20000
forcefield_option: gaff
gpu_devices: [1,2,3,4]
kforce_displ: 2.5
kforce_psi: 50.0
kforce_theta: 50.0
kforce_vsite: 0
ligand_dpathname: ./001.prep/ligands
morph_fpathname: null
morph_type: star
print_energy_interval: 20000
print_traj_interval: 60000
protein_fpathname: null
ref_alignidx: null
ref_ligdG: 0.0
ref_ligname: Compd-0044102
sim_time: 5.0
vsite_radius: 5.0
work_dir: /Users/ericchen/tmp/test_conf0
