abfe_ligands: null
atm_type: rbfe
atom_build_pathname: ~/github/AToM-OpenMM
atm_pythonpathname: ~/miniconda3/envs/atm-dev/bin/python
is_slurm: True
partition: any # the partition of hpc to run atm
cofactor_fpathname: ./001.prep/cofactors/GDP/cofactor.sdf
protein_fpathname: ./001.prep/proteins/KRAS/protein.pdb
displ_vec: null
disregard_ratio: 0.3
dt: 0.002
exchange_interval: 20000
forcefield_option: gaff2 # forcefield for ligands/cofactor, [gaff2, openff] 
gres: 2  # the gres requested by atm job when on slurm
gpu_devices: [0,1,2,3] # if not slurm, control which gpu to use
kforce_displ: 2.5
kforce_psi: 50.0
kforce_theta: 50.0
kforce_vsite: 0
ligand_dpathname: ./001.prep/ligands
morph_fpathname: null
morph_type: star
print_energy_interval: 20000
print_traj_interval: 60000
ref_alignidx: [35,4,16]
ref_ligdG: 0.0
ref_ligname: Compd-0044102
sim_time: 2.0
vsite_radius: 5.0
work_dir: .
